# config.yaml

# apk directory
apk_path: D:\duokong\apkfile

# apk name
apk_name: tv.danmaku.bili

# ld directory
ld_path: D:\leidian\LDPlayer9

# proxy switch
proxy_switch: false

# start num
run_num: 2

# step： click：x,y，sleep：s ，swipe：x1,y1,x2,y2
action:
  step0:
    sleep: 5
    click: 360, 900
  step1:
    sleep: 5
    click: 439,195
  step2:
    sleep: 5
    click: 545,195
  step3:
    sleep: 5
    click: 220,195
  step4:
    sleep: 5
    click: 169,196
  step5:
    sleep: 5
    click: 349, 293
  step6:
    sleep: 5
    press: BACK


