# 配置文件

# apk存放路径文件夹（不要含有中文路径）
apk_path: D:\lin\pyproject\duokong\apkfile

# apk包名
apk_name: tv.danmaku.bili

# 雷电安装路径
ld_path: D:\leidian\LDPlayer9

# 使用代理开关
proxy_switch: false

# 设置启动的设备数量
run_num: 10

# 操作步骤： click：点击(坐标)，sleep：等待时间(秒) ，swipe：滑动屏幕(坐标)
action:
  step0:
    sleep: 5
    click: 360, 900
  step1:
    sleep: 5
    click: 439,195
  step2:
    sleep: 5
    click: 545,195
  step3:
    sleep: 5
    click: 220,195
  step4:
    sleep: 5
    click: 169,196
  step5:
    sleep: 5
    swipe: 460, 330, 320, 330
  step6:
    sleep: 5
    click: 349, 293
  step7:
    sleep: 10
    press: BACK


